### ISSUE TITLE
simplify `addDataEntry!`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#391]
## Tasks

- [ ] Clarify on differences between current `FileDataStore` and `InMemDataStore`
- [ ] vote on API including standardized Noun(s) to use
- [ ] implement simplified function and background DataStore pointers
- [x] Update [Noun/keyword definitions on the wiki](https://juliarobotics.org/Caesar.jl/latest/dev/wiki/).
- [x] open corresponding issue for getDataEntry! (see #392 )

## Description

Perhaps simplify the current:
```julia
    # Make a big data entry in the graph - use JSON2 to just write this (really really verbosely)
    element = GeneralBigDataEntry(fg, systemstate.cur_variable, :RADAR, mimeType="application/json")
    # # Set it in the store
    addBigData!(datastore, element, Vector{UInt8}(JSON2.write(msg)))
    # # Add the entry to the graph
    addBigDataEntry!(systemstate.cur_variable, element)
```

to this:
```julia
addDataElement!(dfg, :var|:fct, :RADAR, JSON2.write(msg), mimeType="application/json")
```

### Two Current Implementations for InMemory?

What is the difference between these two:
- https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/master/src/BigData/services/InMemoryDataStore.jl
- https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/master/src/BigData/services/FileDataStore.jl

### Must Define Nouns and keywords

- `Entry` :heavy_check_mark: 
- `Element` :heavy_check_mark: 

Also
- `mimeType` :heavy_check_mark: 

## Related
- JuliaRobotics/Caesar.jl#514

**Comment by Affie** [comment]
I think it can be a convenience wrapper, but please leave the separate functionality of `addBigDataEntry`

**Comment by dehann** [comment]
Hi @Affie , cool thanks will do.  Next question, do you perhaps know the difference between FileDataStore and InMemoryDataStore (see links in first comment above)?

**Comment by dehann** [comment]
Again, I believe we decided against `BigData` as Noun and only using `Data` and `Smalldata` as Nouns.
